version: "3"
services:
  database:
    # Dockerfile이 있는 위치
    build: ./database
    # 내부에서 개방할 포트 : 외부에서 접근할 포트
    ports:
      - "3002:3306"
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3001:8000"
  frontend:
    build: ./frontend
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    # volumes:
    #   - ./frontend:/home/node/app
    ports:
      - "3000:3000"
